---
title: "Edit EML"
format: html
---


```{r, child = '../training/workflows/edit_eml/edit_an_eml_element.qmd'}
```


```{r, child = '../training/workflows/edit_eml/edit_attributelists.qmd'}
```


```{r, child = '../training/workflows/edit_eml/edit_custom_units.qmd'}
```


```{r, child = '../training/workflows/edit_eml/edit_datatables.qmd'}
```

```{r, child = '../training/workflows/edit_eml/edit_semantic_annotation.qmd'}
```


```{r, child = '../training/workflows/edit_eml/edit_spatialdata.qmd'}
```


```{r, child = '../training/workflows/edit_eml/format_text.qmd'}
```


```{r, child = '../training/workflows/edit_eml/series_identifier.qmd'}
```

```{r, child = '../training/workflows/edit_eml/set_coverages.qmd'}
```


```{r, child = '../training/workflows/edit_eml/set_methods.qmd'}
```


```{r, child = '../training/workflows/edit_eml/set_parties.qmd'}
```


```{r, child = '../training/workflows/edit_eml/set_physical.qmd'}
```

```{r, child = '../training/workflows/edit_eml/set_project.qmd'}
```


```{r, child = '../training/workflows/edit_eml/use_references.qmd'}
```
